# Generated by Django 2.2 on 2019-04-29 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interests',
            new_name='Interest',
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='Socials',
            new_name='Social',
        ),
        migrations.RenameModel(
            old_name='WebsiteSections',
            new_name='WebsiteSection',
        ),
    ]
