# Generated by Django 2.2 on 2019-05-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190429_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='url',
            field=models.CharField(max_length=128),
        ),
    ]
