# Generated by Django 2.2 on 2019-05-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190504_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='image',
            field=models.ImageField(upload_to='social_icons'),
        ),
    ]
