# Generated by Django 2.2 on 2019-05-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='resume',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
